# Настройки pytest для всего проекта.
[pytest]
# pythonpath = .  добавляет корень проекта в пути поиска модулей.
# Благодаря этому в тестах работает импорт "from pages.login_page import LoginPage".
pythonpath = .